### ISSUE TITLE
recompile after activating

### ISSUE THREAD

**Issue by sirfoga** [ChrisRackauckas/universal_differential_equations#23]
Do I really need to recompile every package (`OrdinaryDiffEq`, `ModelingToolki` ...) after `Pkg.activate("."); Pkg.instantiate()` ? It seems to be doing so ...

**Comment by ChrisRackauckas** [comment]
It only should be recompiling if that's not the version you have in your global environment. The manifest that this uses is a bit old now, so it probably is slightly different and it's worth an update.
