### ISSUE TITLE
`MethodError: no method matching SInDy` in DelayLotkaVolterra/VolterraExp.jl

### ISSUE THREAD

**Issue by VitaminBrad** [ChrisRackauckas/universal_differential_equations#27]
I'm running the DelayLotkaVolterra/VolterraExp.jl unmodified and I'm getting the following error: 

`MethodError: no method matching SInDy`

![](https://i.imgur.com/RwpeQMo.png)

Thanks!

**Comment by ChrisRackauckas** [comment]
@AlCap23 ?

**Comment by ChrisRackauckas** [comment]
Looks like the version in here still has f_target but the manifest updated to the Pareto?

**Comment by AlCap23** [comment]
Ah, I forgot that we didn't include compat bounds right now.

Should be fixed via #28 . Thanks for the notification!

**Comment by VitaminBrad** [comment]
Hey all, thanks for the attention!

My above error was happening within Jupyter notebook without the project.toml file whatsoever. 

I've since cloned the entire repo and now I'm trying to run it in Juno instead but I get the following when I try to run the VolterraExp.jl script. 

![](https://i.imgur.com/gTlahMG.png)

My apologies - I'm still a super noob in Julia. >_<"

I'm going to go through the workshop from JuliaCon2020 now and see if building it up from scratch will get me there eventually instead - I was trying to leapfrog (perhaps a bit too much) to see if I could throw a complicated set of 45 equations of a reaction network into the toy problem. 
![](https://i.imgur.com/cSW4E75.png)

**Comment by ChrisRackauckas** [comment]
It's not your fault. The GPU library changed from v1.4 to v1.5 and the manifest for these examples uses the v1.4 versions. They will need an update to work on Julia v1.5.

**Comment by VitaminBrad** [comment]
Ah, I see. All good. If I have a deadline in 3 weeks, would you recommend I downgrade to Julia v1.4 for the time being?

Thanks again for all you/your teams' help (& diligent/ground-breaking work)!

**Comment by ChrisRackauckas** [comment]
I'd say just use v1.4 for now. It's not that different (though compile times are longer). I think @AlCap23 might've just figured out what was up with that test yesterday though.

**Comment by VitaminBrad** [comment]
Hi again, 
I'm experiencing the following on 1.4.2:
![](https://i.imgur.com/d0gqBZF.png)

**Comment by ChrisRackauckas** [comment]
Using the manifest?

**Comment by AlCap23** [comment]
What's your version of DataDriven?

**Comment by VitaminBrad** [comment]
> Using the manifest?

A different Project.toml was being used... I have since educated myself on Pkg.instatiate(), Project.toml, and Manifest.toml.

Thank you. This can be closed.

**Comment by ChrisRackauckas** [comment]
I think we'll leave this open until we update it for the latest DataDriven. This repo is looked at enough that it's good to keep it up to date.
